# This is a basic workflow to help you get started with Actions

name: Release



# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile latex code
        uses: xu-cheng/latex-action@3.2.0
        with: 
          root_file: main.tex
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: main.pdf
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
            
